### ISSUE TITLE
Error when importing from typescript

### ISSUE THREAD

**Issue by n9** [hermanwikner/react-connect-lines#1]
```
import { ConnectProvider } from "react-connect-lines"
```

Causes error:
> Could not find a declaration file for module 'react-connect-lines'. 'node_modules/react-connect-lines/dist/esm/index.js' implicitly has an 'any' type.
> There are types at 'node_modules/react-connect-lines/dist/types/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'react-connect-lines' library may need to update its package.json or typings.ts(7016)

**Comment by RileyManda** [comment]
> ```
> import { ConnectProvider } from "react-connect-lines"
> ```
> 
> Causes error:
> 
> > Could not find a declaration file for module 'react-connect-lines'. 'node_modules/react-connect-lines/dist/esm/index.js' implicitly has an 'any' type.
> > There are types at 'node_modules/react-connect-lines/dist/types/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'react-connect-lines' library may need to update its package.json or typings.ts(7016)

This library certainly has issues in typescript projects.I am also unable to use it in my typescript project.

**Comment by hermanwikner** [comment]
Sorry about this—I don't actively maintain this project, but this should be fixed now in version `0.0.4`.
